CREATE TABLE `ai_writers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`slug` varchar(128) NOT NULL,
	`avatarUrl` text,
	`bio` text,
	`tone` varchar(128),
	`persona` text,
	`writingStyle` text,
	`forbiddenWords` text,
	`sampleText` text,
	`languages` varchar(256) NOT NULL DEFAULT 'ja',
	`categorySpecialties` varchar(512),
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_writers_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_writers_slug_unique` UNIQUE(`slug`)
);
